//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Votacao.Dominio {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Avisos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Avisos() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Votacao.Dominio.Avisos", typeof(Avisos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo maior que o esperado..
        /// </summary>
        internal static string Campo_maior_que_o_esperado {
            get {
                return ResourceManager.GetString("Campo_maior_que_o_esperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo obrigatório..
        /// </summary>
        internal static string Campo_obrigatorio {
            get {
                return ResourceManager.GetString("Campo_obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esse usuário já votou..
        /// </summary>
        internal static string Esse_usuario_ja_votou {
            get {
                return ResourceManager.GetString("Esse_usuario_ja_votou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filme Apagado com sucesso!.
        /// </summary>
        internal static string Filme_Apagado_com_sucesso {
            get {
                return ResourceManager.GetString("Filme_Apagado_com_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filme Atualizado com sucesso!.
        /// </summary>
        internal static string Filme_Atualizado_com_sucesso {
            get {
                return ResourceManager.GetString("Filme_Atualizado_com_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filme Gravado com sucesso!.
        /// </summary>
        internal static string Filme_Gravado_com_sucesso {
            get {
                return ResourceManager.GetString("Filme_Gravado_com_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id inválido. Este Id não está cadastrado..
        /// </summary>
        internal static string Id_invalido_Este_Id_nao_esta_cadastrado {
            get {
                return ResourceManager.GetString("Id_invalido_Este_Id_nao_esta_cadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login já existente. Por favor, tente um login diferente..
        /// </summary>
        internal static string Login_ja_existente_Por_favor_tente_um_login_diferente {
            get {
                return ResourceManager.GetString("Login_ja_existente_Por_favor_tente_um_login_diferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login ou Senha inválidos..
        /// </summary>
        internal static string Login_ou_Senha_invalidos {
            get {
                return ResourceManager.GetString("Login_ou_Senha_invalidos", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pontuacao Invalida..
        /// </summary>
        internal static string Pontuacao_Invalida
        {
            get
            {
                return ResourceManager.GetString("Pontuacao_Invalida", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, corrija as inconsistências abaixo..
        /// </summary>
        internal static string Por_favor_corrija_as_inconsistências_abaixo {
            get {
                return ResourceManager.GetString("Por_favor_corrija_as_inconsistências_abaixo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario Apagado com sucesso!.
        /// </summary>
        internal static string Usuario_Apagado_com_sucesso {
            get {
                return ResourceManager.GetString("Usuario_Apagado_com_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário Atualizado com sucesso!.
        /// </summary>
        internal static string Usuario_Atualizado_com_sucesso {
            get {
                return ResourceManager.GetString("Usuario_Atualizado_com_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário Autenticado com sucesso!.
        /// </summary>
        internal static string Usuario_Autenticado_com_sucesso {
            get {
                return ResourceManager.GetString("Usuario_Autenticado_com_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario Gravado com sucesso!.
        /// </summary>
        internal static string Usuario_Gravado_com_sucesso {
            get {
                return ResourceManager.GetString("Usuario_Gravado_com_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voto realizado com sucesso!.
        /// </summary>
        internal static string Voto_realizado_com_sucesso {
            get {
                return ResourceManager.GetString("Voto_realizado_com_sucesso", resourceCulture);
            }
        }
    }
}
